server:
   port: 8080
   contextPath: /
spring:
  redis:
    host: 123.59.84.71
    port: 6379
    password: 9hcom.com
  http:
    multipart:
      max-file-size: 50M
      max-request-size: 100M
# DATASOURCE
#jdbc:
#    driverClass: com.mysql.jdbc.Driver
#    url: jdbc:mysql://hfc.dbdbd.cn/oauth2-user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior
#    username: hfc
#    password: lucifer-hfc
#jdbc-hfc:
#    driverClass: com.mysql.jdbc.Driver
#    url: jdbc:mysql://hfc.dbdbd.cn/hfc?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior
#    username: hfc
#    password: lucifer-hfc

jdbc:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/oauth2-user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior
    username: root
    password:
jdbc-hfc:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/hfc?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior
    username: root
    password:


# MyBatis

mybatis:
    typeAliasesPackage: com.lucifer
    mapperLocations: classpath:/sqlmaps/*.xml
    configLocation: classpath:/mybatis-config.xml

qiniu:
  accessKey: eeYtcWvGPXqjEiTIxDljeVu8qxFpwdXOvGo4PURq
  secretKey: LHkSG-HRLccuUYSgb-TX0ZcDrsyUMEzSg6Z3GG6G
  publicBucket: hfc-lucifer
  url: http://ojvbqldpg.bkt.clouddn.com/
multipart:
  maxFileSize: 10Mb
  maxRequestSize: 30Mb





