server:
   port: 8080
   contextPath: /
spring:
  redis:
    host: 123.59.84.71
    port: 6379
    password: 9hcom.com
# DATASOURCE
jdbc:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.dbdbd.cn/oauth2-user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior
    username: root
    password: lucifer
jdbc-hfc:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.dbdbd.cn/hfc?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior
    username: root
    password: lucifer
# MyBatis

mybatis:
    typeAliasesPackage: com.lucifer
    mapperLocations: classpath:/sqlmaps/*.xml
    configLocation: classpath:/mybatis-config.xml

qiniu:
  accessKey: eeYtcWvGPXqjEiTIxDljeVu8qxFpwdXOvGo4PURq
  secretKey: LHkSG-HRLccuUYSgb-TX0ZcDrsyUMEzSg6Z3GG6G
  publicBucket: hfc-lucifer
  url: http://ojvbqldpg.bkt.clouddn.com/
multipart:
  maxFileSize: 10Mb
  maxRequestSize: 30Mb





